import type { MarketCandidate } from "./types";

export const mockMarkets: MarketCandidate[] = [
  {
    provider: "kalshi",
    id: "KXRAIN-AUS-2026OCT12",
    sourceUrl: "https://kalshi.com/markets/KXRAIN-AUS-2026OCT12",
    title: "Will Austin record heavy rain on Oct 12, 2026?",
    rules:
      "Resolves Yes if the official Austin weather station records at least 1 inch of rain on Oct 12, 2026.",
    riskType: "weather_event",
    location: "Austin",
    closeTime: "2026-10-12T12:00:00.000Z",
    resolutionTime: "2026-10-13T18:00:00.000Z",
    outcomes: ["yes", "no"],
    bestBid: 0.29,
    bestAsk: 0.32,
    liquidity: 42000,
    openInterest: 118000,
    status: "open",
    executionMode: "demo",
    tags: ["weather", "rain", "austin", "event"],
  },
  {
    provider: "kalshi",
    id: "KXSTORM-TX-2026OCT",
    sourceUrl: "https://kalshi.com/markets/KXSTORM-TX-2026OCT",
    title: "Will a named storm affect Texas in October 2026?",
    rules:
      "Resolves Yes if a named storm leads to a National Weather Service warning in Texas during October 2026.",
    riskType: "weather_event",
    location: "Texas",
    closeTime: "2026-10-31T23:00:00.000Z",
    resolutionTime: "2026-11-02T18:00:00.000Z",
    outcomes: ["yes", "no"],
    bestBid: 0.18,
    bestAsk: 0.22,
    liquidity: 18000,
    openInterest: 86000,
    status: "open",
    executionMode: "demo",
    tags: ["weather", "storm", "texas", "event"],
  },
  {
    provider: "polymarket",
    id: "PM-RAIN-US-SOUTH-OCT",
    sourceUrl: "https://polymarket.com/event/us-south-severe-rainfall-event-in-october-2026",
    title: "US South severe rainfall event in October 2026?",
    rules:
      "Resolves according to a public severe weather bulletin for the US South region during October 2026.",
    riskType: "weather_event",
    location: "US South",
    closeTime: "2026-10-31T23:00:00.000Z",
    resolutionTime: "2026-11-03T18:00:00.000Z",
    outcomes: ["yes", "no"],
    bestBid: 0.21,
    bestAsk: 0.26,
    liquidity: 12000,
    openInterest: 54000,
    status: "open",
    executionMode: "read_only",
    tags: ["weather", "rain", "regional"],
  },
  {
    provider: "kalshi",
    id: "KXHORMUZ-2026Q4",
    sourceUrl: "https://kalshi.com/markets/KXHORMUZ-2026Q4",
    title: "Will the Strait of Hormuz face a major disruption in Q4 2026?",
    rules:
      "Resolves Yes if a listed public source reports a major shipping disruption in the Strait of Hormuz during Q4 2026.",
    riskType: "shipping_geopolitical",
    location: "Middle East",
    closeTime: "2026-12-31T23:00:00.000Z",
    resolutionTime: "2027-01-04T18:00:00.000Z",
    outcomes: ["yes", "no"],
    bestBid: 0.12,
    bestAsk: 0.16,
    liquidity: 7000,
    openInterest: 30000,
    status: "open",
    executionMode: "simulated",
    tags: ["shipping", "geopolitical", "oil", "route"],
  },
  {
    provider: "kalshi",
    id: "KXCPI-2026OCT",
    sourceUrl: "https://kalshi.com/markets/KXCPI-2026OCT",
    title: "Will US CPI exceed 3 percent for October 2026?",
    rules:
      "Resolves Yes if the official CPI report for October 2026 is above 3 percent year over year.",
    riskType: "macro_event",
    location: "United States",
    closeTime: "2026-11-15T15:00:00.000Z",
    resolutionTime: "2026-11-16T18:00:00.000Z",
    outcomes: ["yes", "no"],
    bestBid: 0.42,
    bestAsk: 0.46,
    liquidity: 55000,
    openInterest: 220000,
    status: "open",
    executionMode: "demo",
    tags: ["macro", "inflation", "cpi"],
  },
];
